[build]
  command = "npm run build:netlify"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9.8.1"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
